name: Java CI with Maven

on: [push]

permissions:
  contents: write  # necessario per creare la GitHub release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8.0.332+9
        cache: 'maven'

    - name: Get version
      id: version
      run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

    - name: Get changelog
      id: changelog
      run: echo "changelog=$(git log --pretty=format:'%h %s' $(git describe --tags --abbrev=0)..HEAD)" >> $GITHUB_OUTPUT

    - name: "[1/5] Compile project"
      run: mvn compile

    - name: "[2/5] Test project"
      run: mvn test

    - name: "[3/5] Static Analysis"
      run: mvn verify

    - name: "[4/5] Upload to Coveralls"
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: target/site/jacoco/jacoco.xml

    - name: "[5/5] Release project"
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        body: ${{ steps.changelog.outputs.changelog }}
        name: Release ${{ steps.version.outputs.version }}
        tag_name: v${{ steps.version.outputs.version }}